version: "3.2"

services:
  postgres:
    image: postgres:11.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: defaultdb

  redis:
    image: redis:6.0-alpine
    ports:
     - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master

